### PR TITLE
[WIP] Code for NPQ-25 (Skill Use) and NPQ-22 (Projectile)

### PR DESCRIPTION
**Pull request by maxilevi**
This Pull Request contains the code necessary to fix both issues NPQ-25 (Skill Use) and NPQ-22 (Projectile). This is not the final version. It's still a work in progress and it will be updated frequently.

### CODE REVIEW

**Review by Snayff — APPROVED** [review]
Surprised to see `screen_x` and `screen_y` changed to `draw_x` and `draw_y` but otherwise looks good.

**Comment by maxilevi** [comment]
> Surprised to see `screen_x` and `screen_y` changed to `draw_x` and `draw_y` but otherwise looks good.

I felt screen_x and screen_y was confusing since the coordinates are not screen coordinates but instead world coordinates. They are transformed to screen coordinates when the camera draws each entity but stored in world/tile coordinates in the Aesthetic component. 

I felt it was justified though I can revert the commit if you prefer the old names, I have no problem with that.

**Comment by Snayff** [comment]
I've found that x and y got confused at some points regarding whether they
mean the tile or the display so I started trying to use `screen_x`/y  for
position within the window and `x`/y as the default, to refer to which
tile. So I'm not surprised you thought they were confusing, too!

Its no problem, lets stick with `draw_x`/y.

**Comment by Snayff** [comment]
Found a bug when using a skill. It looks like it knocks the hit entity back to the end of the projectiles range. Could you take a look at that, please?

https://i.imgur.com/SHZsFI7.gifv

**Comment by maxilevi** [comment]
> Found a bug when using a skill. It looks like it knocks the hit entity back to the end of the projectiles range. Could you take a look at that, please?
> 
> https://i.imgur.com/SHZsFI7.gifv

I thought that push was intended. I'll get it fixed. Btw if the enemy is next to you should still be able to cast the projectile right?

**Comment by Snayff** [comment]
Unfortunately not on this skill! I'm not even sure how it happened. If
you're at point blank range you can still cast, yes.

**Pull request merged**
