### PR TITLE
Fix projectile moving entities when used next to them

### PR DESCRIPTION
**Pull request by maxilevi**
The crux of the bug was that the projectile was not detecting it spawned on a tile with another entity, so it executed the 'move' skill and moved both itself and the entity on the same tile. The fix was to make the projectile behaviour correctly detect when it was on another entity and if that was the case it needed to avoid applying the skill on itself. Now everything should work correctly.

[GIF of the bug](https://i.imgur.com/SHZsFI7.gifv)

EDIT: If you want to not make every commit I made show below I think you could merge by doing a rebase, that would apply each of my commits sequentially on the codebase instead of together in one so they would stop appearing in the diff.

EDIT2: Although the commits show, this PR only contains the code for the bug fix.

### CODE REVIEW

**Review by Snayff — APPROVED** [review]
Looks good. Could you describe the reason behind ignoring entities?

**Comment by maxilevi** [comment]
> Looks good. Could you describe the reason behind ignoring entities?

Sure, previously when 2 entities were on the same tile it was impossible to execute an skill (either a move or an attack) without affecting oneself or the other entity. e.g. Previously when you attacked it spawned a projectile in the same position as the enemy so moving the projectile would move the entity too and if we made the projectile to detect that and attack the entity then both the entity and the projectile would get attacked. The ignoring entities allows us to avoid these scenarios.

**Comment by Snayff** [comment]
Ah, got you! So I thought I'd set up the second circumstance where if it
was cast on the same tile as an existing entity it would apply the effect
and then delete itself but I am not sure either of those things happened as
intended!

**Comment by maxilevi** [comment]
> Ah, got you! So I thought I'd set up the second circumstance where if it was cast on the same tile as an existing entity it would apply the effect and then delete itself but I am not sure either of those things happened as intended!

Yes I saw that, I believe you are referring to this piece of code
```python
# if we havent moved check for collision in current tile (it might be cast on top of enemy)
        if self.distance_travelled == 0 and current_tile:
            if world.tile_has_tag(current_tile, TargetTag.OTHER_ENTITY, entity):
                activate = True
                skill_instance = self.data.skill_instance

                # update skill instance to new target
                skill_instance.target_tile = current_tile
```

It never got executed because of the way `world.tile_has_tag(current_tile, TargetTag.OTHER_ENTITY, entity)` worked. Instead the behaviour ended up passing through that code and executing the move skill that moved the projectile and the entity (because they were in the same tile). Part of the fix was to make that piece of code execute correctly and the other part to only execute the skill on the other entity (using the ignore list) so the attack didn't get executed on the projectile.

**Pull request merged**
